### ISSUE TITLE
Lacking Critical Support

### ISSUE THREAD

**Issue by tonylukasavage** [sindresorhus/noop3#1]
Needs support for:
- No CommonJS
- ES6 modules
- ES7 async functions
- MongoDB 3.2 & Postgresql

Can we also get some examples with _non-mythical_ creatures that have single protruding horns? Personally would love to see a narwhal-based example.

**Comment by sindresorhus** [comment]
PR welcome! Should include tests and a song.

**Comment by yordis** [comment]
LOOOOOOOOOL
