### ISSUE TITLE
Needs more extensive testing

### ISSUE THREAD

**Issue by RReverser** [sindresorhus/noop3#10]
Currently tests only check that function returns `undefined`, which doesn't guarantee that it does really _NOTHING_. Needs more detailed tests that check against all the possible side-effects by comparing snapshots of environment before and after execution.

**Comment by sindresorhus** [comment]
Agreed. What was I thinking... PR welcome! :santa:

**Comment by Go7hic** [comment]
what this!!!!!!
![Imgur](http://i.imgur.com/8SHOpll.png?1)
