### ISSUE TITLE
needs 500% test coverage; Nothing should not do anything.

### ISSUE THREAD

**Issue by radiovisual** [sindresorhus/noop3#11]
Currently, you have 100% test coverage, which normally is sufficient, but when you are testing the incalculable vast of nothingness, you need test coverage that gets you closer to `Infinity%`. 

We can start by testing that `nothing doesn't do anything`, and increasing the code coverage to 500%.

``` js
test('nothing should not do anything', t => {
    t.throws(() => {
        noop3().doSomething();
        noop3().doAnythingAtAll();
        noop3().seriouslyJustTrySomethingSimpleItIsAllWeAsk();
        noop3().pleaseGetOffYourLazyUnicornBumAndDoSomethingForOnce();
    });
});
```

**Comment by sindresorhus** [comment]
Why not reach Infinity? Do a for loop to Infinity testing it.

**Comment by radiovisual** [comment]
**That's a great idea:** _unit-testing to Infinity!_ 

I have the badges ready:

![500](http://numetriclabs.com/demos/github/500-percent.svg)

![500](http://numetriclabs.com/demos/github/Infinity-percent.svg)

I think that reaching 500% test coverage should be the new standard, and reaching Infinity% test coverage is how you reach unicorn status.

**Comment by radiovisual** [comment]
`Unicorn% === Infinity%`

![500](http://numetriclabs.com/demos/github/unicorn-percent-upper.svg)

**Comment by radiovisual** [comment]
``` js
test.cb('noop3 is eternally useless', t => {
    t.plan(Infinity);

    infiniteArrayofNothingness.map(() => {
        const isNoop3Useless = functionDoesAbsolutelyNothing(noop3);
        t.is(isNoop3Useless, true);
    });
    t.end();
});
```

:stuck_out_tongue_winking_eye: :hamburger:

**Comment by sindresorhus** [comment]
PR welcome! :D
