### ISSUE TITLE
how to dislike a package? #ï͂͑̉͆ͧͮͩ̓ͧ̒͒̉̎̂̊͆͑͐̊̓̊̅ͭ͗̐̄̏̾̄͊ͭͥ̐ͭ͊͐̉͗ͪ͐͊̽ͮ͑ͬͨͤ͒ͦ̿̈̽ͭͤ̃͌͂̅̄ͨ̐̐ͮͭͪ̈̑͐ͥ̊ͮͩ͋ͫ͂̇̐ͣ͒̊̅ͥ̓͐͊̍̑́̾̋̑̎́̍̔͐̓̃̀͆ͭͩ̌͒ͣ͆̒ͯ̎ͯ͒ͩ̐̓ͩͫ̃͑͋̓͆̎́̑͋̊̐́͐ͧ̀͛ͩ̐̓ͩ̚#ï͂͑̉͆ͧͮͩ̓ͧ̒͒̉̎̂̊͆͑͐̊̓̊̅ͭ͗̐̄̏̾̄͊ͭͥ̐ͭ͊͐̉͗ͪ͐͊̽ͮ͑ͬͨͤ͒ͦ̿̈̽ͭͤ̃͌͂̅̄ͨ̐̐ͮͭͪ̈̑͐ͥ̊ͮͩ͋ͫ͂̇̐ͣ͒̊̅ͥ̓͐͊̍̑́̾̋̑̎́̍̔͐̓̃̀͆ͭͩ̌͒ͣ͆̒ͯ̎ͯ͒̚

### ISSUE THREAD

**Issue by nzmedet** [sindresorhus/noop3#18]
you have done a lot of  "̋̏̏̏̋̏̏̋̋̏̏̋̋̏̋̏̋̏̏̋̏̏̋̋̏̏̏̋̋̏̋̋̏̏̋̋̋̏̏̋̋̋̋̋̏̋̏̏̏̋̏̏̏̋̋̏̏̋̋̋̏̋̏̋̋̋̋̏̏̏̋̏̏̋̋̏̋̏̋̋̋̋̏̏̏̋̋̏̋̏̏̋̋̋̋̋̋̋̋̏̋̏̏̏̏̏̏̋̏̋̏̏̏̋̋̏̏̏̏̋̏̋̋̋̋̏̏̏̋̋̋̋̋̏̏̏̏̏̋ه҈̿҈̿҈̿҈̿҈̿҈̿҈̿҈̿҈̿҈̿҈̿҈̿҈̿҈ه҈̿҈̿҈̿҈̿҈̿҈̿҈̿҈̿҈̿҈̿҈̿҈̿҈̿҈ه҈̿҈̿҈̿҈̿҈̿҈̿҈̿҈̿҈̿҈̿҈̿҈̿҈̿҈ه҈̿҈̿҈̿҈̿҈̿҈̿҈̿҈̿҈̿҈̿҈̿҈̿҈̿҈ه҈̿ useful things, but those kind of things make me belive we fucking lost the cursor of software development, i don't like this package, is there any way to dislike a github project?

**Comment by sindresorhus** [comment]
ه҈҈̚̚̚̚̚̚̚̚̚҉̚҉̚҈҈̚̚̚̚̚̚̚̚̚҉̚҉̚҈҈̚̚̚̚̚̚̚̚̚҉̚҉̚҈҈̚̚̚̚̚̚̚̚̚҉̚҉̚҈҈̚̚̚̚̚̚̚̚̚҉̚҉̚҈҈̚̚̚̚̚̚̚̚̚҉̚҉̚҈҈̚̚̚̚̚̚̚̚̚҉̚҉̚҈҈̚̚̚̚̚̚̚̚̚҉̚҉̚҈҈̚̚̚̚̚̚̚̚̚҉̚҉̚ ه҈҈̚̚̚̚̚̚̚̚̚҉̚҉̚҈҈̚̚̚̚̚̚̚̚̚҉̚҉̚҈҈̚̚̚̚̚̚̚̚̚҉̚҉̚҈҈̚̚̚̚̚̚̚̚̚҉̚҉̚҈҈̚̚̚̚̚̚̚̚̚҉̚҉̚҈҈̚̚̚̚̚̚̚̚̚҉̚҉̚҈҈̚̚̚̚̚̚̚̚̚҉̚҉̚҈҈̚̚̚̚̚̚̚̚̚  You can vote 👎 with GitHub reactions.  ҈̒̓̕҈̒̓̕҈̒̓̕҈̒̓̕҈̒̓̕҈̒̓̕҈̒̓̕҈̒̓̕҈̒̓̕҈̒̓̕҈̒̓̕҈̒̓̕҈̒̓̕҈̒̓̕҈̒̓̕҈̒̓̕҈̒̓̕҈̒̓̕҈̒̓̕҈̒̓̕҈̒̓̕҈̒̓̕҈̒̓̕҈̒̓̕҈̒̓̕҈̒̓̕҈̒̓̕҈̒̓̕҈̒̓̕҈̒̓̕҈̒̓̕҈̒̓̕҈̒̓̕҈̒̓̕҈̒̓ ҈̒̓̕҈̒̓̕҈̒̓̕҈̒̓̕҈̒̓̕҈̒̓̕҈̒̓̕҈̒̓̕҈̒̓̕҈̒̓̕҈̒̓̕҈̒̓̕҈̒̓̕҈̒̓̕҈̒̓̕҈̒̓̕҈̒̓̕҈̒̓̕҈̒̓̕҈̒̓̕҈̒̓̕҈̒̓̕҈̒̓̕҈̒̓̕҈̒̓̕҈̒̓̕҈̒̓̕҈̒̓̕҈̒
