### ISSUE TITLE
Congratulations, it's awesome!

### ISSUE THREAD

**Issue by inikulin** [sindresorhus/noop3#2]
Just released https://github.com/inikulin/noop-fn a couple days ago. Awesome gif in readme and named function: damn, yours is much better! :disappointed: Should I add obsoletion note in regard of this package?

**Comment by sindresorhus** [comment]
Oh, haha. I was inspired by [`noop2`](https://github.com/yoshuawuyts/noop2) :p

Can never have too many noop modules! Keep it.
