### ISSUE TITLE
async version?

### ISSUE THREAD

**Issue by lararosekelley** [sindresorhus/noop3#20]
ideally supporting es7 async / await

**Comment by sindresorhus** [comment]
👍 Pull request welcome :)

**Comment by blade254353074** [comment]
Why we need async noop3?
Since `await` can take over promisify/non-promisify function.

```js
async function asyncFunc () {
  await noop3()
}

function syncFunc () {
  noop3()
}

// What's diff?
```

**Comment by SamVerschueren** [comment]
> // What's diff?

Non-blocking!!!!!

**Comment by blade254353074** [comment]
😂 All right, I believed.

**Comment by lararosekelley** [comment]
async isn't real, closing issue
