### ISSUE TITLE
I love this package! Could you make more pkgs like this?

### ISSUE THREAD

**Issue by blade254353074** [sindresorhus/noop3#24]
This kind of packages are awesome!

Wish you can make more pkgs like this. 😝

**Comment by blade254353074** [comment]
And do we need a seemingly decent logo?

**Comment by sindresorhus** [comment]
It already has a perfect logo though.

**Comment by blade254353074** [comment]
Just kidding...
Current logo is very impressive 😂.

**Comment by sindresorhus** [comment]
You might also like my [`superheroes`](https://github.com/sindresorhus/superheroes) and [`dofle`](https://github.com/sindresorhus/dofle) module.

**Comment by blade254353074** [comment]
Hahaha, gotcha!

![image](https://user-images.githubusercontent.com/9346008/27183078-eda50216-520f-11e7-9c76-e690277544ab.png)
<sub>Nice photo (and cat) </sub>
