### ISSUE TITLE
Uni-queue-ity 

### ISSUE THREAD

**Issue by fregante** [sindresorhus/noop3#26]
https://github.com/search?q=topic%3Asom-tam&type=Repositories

**Comment by sindresorhus** [comment]
![687474703a2f2f7777772e7265616374696f6e676966732e636f6d2f77702d636f6e74656e742f67616c6c6572792f64616e63652d70617274792f74756d626c725f6d306f73727268714d6b31717a6376376e6f345f3235302e676966](https://user-images.githubusercontent.com/170270/28013608-e2f465ce-6569-11e7-91eb-88cfe046c3e8.gif)
