### ISSUE TITLE
Weird characters in issues page

### ISSUE THREAD

**Issue by francisbrito** [sindresorhus/noop3#27]
<img width="918" alt="screen shot 2018-05-06 at 1 22 27 pm" src="https://user-images.githubusercontent.com/2180822/39676077-16a7f534-5132-11e8-936e-79b2eca04e68.png">

Not sure if this is on purpose or if there is something going wrong with GitHub atm.
I checked on:
- Chrome 66, macOS High Sierra 10.13.4
- FireFox Developer Edition 61.0b2, macOS High Sierra 10.13.4
- Chrome for Android

**Comment by esetnik** [comment]
Wow I see the same thing!
