### ISSUE TITLE
performance tests and comparisons

### ISSUE THREAD

**Issue by jokeyrhyme** [sindresorhus/noop3#6]
Do we know how fast `noop3` is?

How much faster is it than [`lodash.noop`](https://lodash.com/docs#noop)?

Or [`jQuery.noop`](http://api.jquery.com/jQuery.noop/)?

We should also experiment with using child processes or Web Workers to offload the task of doing nothing so that we can do nothing without blocking the main thread.

**Comment by sindresorhus** [comment]
Great idea! By doing this I'm supremely confident we could boost the performance tenfold of nothing.
