### ISSUE TITLE
add .eslintrc

### ISSUE THREAD

**Issue by alkhe** [sindresorhus/noop3#8]
I'm not comfortable with using code that's not linted. Like, are you kidding me? What if someone submits a PR without a semicolon or an incompatible indentation style? And typos might go unnoticed too. Please add linting as soon as possible.

**Comment by SamVerschueren** [comment]
It is linted with [XO](https://github.com/sindresorhus/xo).

https://github.com/sindresorhus/noop3/blob/master/package.json#L16

**Comment by alkhe** [comment]
My bad. Can we add an eslint for contributors? Since not everyone uses XO.

**Comment by SamVerschueren** [comment]
XO uses ESLint underneath and is ran when executing `npm test`. Don't see why we should add an extra  eslint file. If we follow these rules, we should add jscs and jshint as well ;).

**Comment by alkhe** [comment]
It's inconvenient when actually coding, though. I'd prefer to have my code linted live.

+1 for jscs and jshint.

**Comment by SamVerschueren** [comment]
Here you go: https://github.com/sindresorhus/xo#editor-plugins
